-- Quiz 3 NFL Trivia database
-- Fixed snapshot: 2025 NFL season plus stable NFL history

CREATE DATABASE IF NOT EXISTS quiz3
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE quiz3;

CREATE TABLE IF NOT EXISTS questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  question_text VARCHAR(500) NOT NULL,
  option_a VARCHAR(255) NOT NULL,
  option_b VARCHAR(255) NOT NULL,
  option_c VARCHAR(255) NOT NULL,
  option_d VARCHAR(255) NOT NULL,
  correct_option CHAR(1) NOT NULL,
  difficulty ENUM('easy', 'hard') NOT NULL,
  category VARCHAR(100) NOT NULL,
  season_year INT NOT NULL DEFAULT 2025,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  UNIQUE KEY uq_question_snapshot (question_text, season_year),
  INDEX idx_questions_lookup (difficulty, is_active, season_year),
  CHECK (correct_option IN ('A', 'B', 'C', 'D'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS scores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  player_name VARCHAR(100) NOT NULL,
  mode ENUM('sudden_death', 'general') NOT NULL,
  difficulty ENUM('easy', 'hard') NOT NULL,
  score INT NOT NULL,
  total_questions INT NOT NULL,
  performance_title VARCHAR(50) NOT NULL,
  played_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_leaderboard (mode, difficulty, score DESC, played_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Starter question bank. INSERT IGNORE keeps reruns from adding duplicates.
INSERT IGNORE INTO questions
(question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, category, season_year, is_active)
VALUES
('Which quarterback won AP NFL MVP for the 2025 season?', 'Josh Allen', 'Matthew Stafford', 'Patrick Mahomes', 'Lamar Jackson', 'B', 'easy', 'award winner', 2025, 1),
('Which team did Matthew Stafford play for in the fixed 2025 snapshot?', 'Los Angeles Rams', 'Detroit Lions', 'Dallas Cowboys', 'Seattle Seahawks', 'A', 'easy', 'player-to-team', 2025, 1),
('Who led the NFL in passing yards during the 2025 regular season?', 'Dak Prescott', 'Jared Goff', 'Matthew Stafford', 'Drake Maye', 'C', 'easy', 'stat leader', 2025, 1),
('Who led the NFL in rushing yards during the 2025 regular season?', 'Derrick Henry', 'James Cook', 'Jonathan Taylor', 'Bijan Robinson', 'B', 'easy', 'stat leader', 2025, 1),
('Who led the NFL in receiving yards during the 2025 regular season?', 'Puka Nacua', 'Ja''Marr Chase', 'Jaxon Smith-Njigba', 'Amon-Ra St. Brown', 'C', 'easy', 'stat leader', 2025, 1),
('Which player won AP Offensive Player of the Year for the 2025 season?', 'Jaxon Smith-Njigba', 'Christian McCaffrey', 'Puka Nacua', 'Bijan Robinson', 'A', 'easy', 'award winner', 2025, 1),
('Which player won AP Defensive Player of the Year for the 2025 season?', 'T.J. Watt', 'Micah Parsons', 'Myles Garrett', 'Nick Bosa', 'C', 'easy', 'award winner', 2025, 1),
('Which team did Myles Garrett play for in the fixed 2025 snapshot?', 'Cleveland Browns', 'Pittsburgh Steelers', 'Houston Texans', 'New York Giants', 'A', 'easy', 'player-to-team', 2025, 1),
('Which player won AP Offensive Rookie of the Year for the 2025 season?', 'Ashton Jeanty', 'Tetairoa McMillan', 'Travis Hunter', 'Cam Ward', 'B', 'easy', 'award winner', 2025, 1),
('Which player won AP Defensive Rookie of the Year for the 2025 season?', 'Abdul Carter', 'Mason Graham', 'Will Johnson', 'Carson Schwesinger', 'D', 'easy', 'award winner', 2025, 1),
('Which NFL team won the Super Bowl for the 2025 season snapshot?', 'Seattle Seahawks', 'Kansas City Chiefs', 'Philadelphia Eagles', 'San Francisco 49ers', 'A', 'easy', 'award/history', 2025, 1),
('Which team does Patrick Mahomes play for?', 'Kansas City Chiefs', 'Buffalo Bills', 'Cincinnati Bengals', 'Baltimore Ravens', 'A', 'easy', 'player-to-team', 2025, 1),
('Which team does Joe Burrow play for?', 'Chicago Bears', 'Cincinnati Bengals', 'New York Jets', 'Tennessee Titans', 'B', 'easy', 'player-to-team', 2025, 1),
('Which team does Lamar Jackson play for?', 'Baltimore Ravens', 'Atlanta Falcons', 'Las Vegas Raiders', 'New Orleans Saints', 'A', 'easy', 'player-to-team', 2025, 1),
('Which team does Josh Allen play for?', 'Buffalo Bills', 'Miami Dolphins', 'Denver Broncos', 'Green Bay Packers', 'A', 'easy', 'player-to-team', 2025, 1),
('How many teams are in the NFL?', '28', '30', '32', '34', 'C', 'easy', 'ring/count', 2025, 1),
('How many points is a touchdown worth before the extra point try?', '3', '6', '7', '8', 'B', 'easy', 'history/rules', 2025, 1),
('What trophy is awarded to the Super Bowl champion?', 'Heisman Trophy', 'Stanley Cup', 'Vince Lombardi Trophy', 'Commissioner''s Trophy', 'C', 'easy', 'history', 2025, 1),
('Which team won the first Super Bowl?', 'Green Bay Packers', 'Dallas Cowboys', 'New York Giants', 'Pittsburgh Steelers', 'A', 'easy', 'history', 2025, 1),
('Which quarterback has won the most Super Bowl rings as a player?', 'Joe Montana', 'Tom Brady', 'Terry Bradshaw', 'Patrick Mahomes', 'B', 'easy', 'ring/count', 2025, 1),
('Which team does Jalen Hurts play for in the fixed 2025 snapshot?', 'Philadelphia Eagles', 'Washington Commanders', 'Dallas Cowboys', 'New York Giants', 'A', 'easy', 'player-to-team', 2025, 1),
('Which team does Brock Purdy play for in the fixed 2025 snapshot?', 'Seattle Seahawks', 'Los Angeles Rams', 'San Francisco 49ers', 'Arizona Cardinals', 'C', 'easy', 'player-to-team', 2025, 1),
('Which team does C.J. Stroud play for in the fixed 2025 snapshot?', 'Houston Texans', 'Indianapolis Colts', 'Jacksonville Jaguars', 'Tennessee Titans', 'A', 'easy', 'player-to-team', 2025, 1),
('Which team does Justin Jefferson play for in the fixed 2025 snapshot?', 'Green Bay Packers', 'Detroit Lions', 'Minnesota Vikings', 'Chicago Bears', 'C', 'easy', 'player-to-team', 2025, 1),
('Which team does Saquon Barkley play for in the fixed 2025 snapshot?', 'New York Giants', 'Philadelphia Eagles', 'Dallas Cowboys', 'Atlanta Falcons', 'B', 'easy', 'player-to-team', 2025, 1),
('Which team does Micah Parsons play for in the fixed 2025 snapshot?', 'Dallas Cowboys', 'Houston Texans', 'Denver Broncos', 'Las Vegas Raiders', 'A', 'easy', 'player-to-team', 2025, 1),
('Which team does T.J. Watt play for in the fixed 2025 snapshot?', 'Cleveland Browns', 'Pittsburgh Steelers', 'Cincinnati Bengals', 'Baltimore Ravens', 'B', 'easy', 'player-to-team', 2025, 1),
('Which team plays its home games at Lambeau Field?', 'Chicago Bears', 'Green Bay Packers', 'Buffalo Bills', 'Minnesota Vikings', 'B', 'easy', 'history', 2025, 1),
('Which conference do the Buffalo Bills play in?', 'NFC', 'Big Ten', 'AFC', 'SEC', 'C', 'easy', 'history/rules', 2025, 1),
('How many conferences are in the NFL?', '2', '4', '6', '8', 'A', 'easy', 'ring/count', 2025, 1),
('How many divisions are in the NFL?', '4', '6', '8', '10', 'C', 'easy', 'ring/count', 2025, 1),
('How many teams are in each NFL conference?', '12', '14', '16', '18', 'C', 'easy', 'ring/count', 2025, 1),
('Which team is known as America''s Team?', 'Dallas Cowboys', 'New England Patriots', 'Green Bay Packers', 'Pittsburgh Steelers', 'A', 'easy', 'history', 2025, 1),
('Which team has a lightning bolt on its helmet?', 'Los Angeles Chargers', 'Tampa Bay Buccaneers', 'Indianapolis Colts', 'Carolina Panthers', 'A', 'easy', 'history', 2025, 1),
('Which city is home to the Dolphins?', 'Orlando', 'Miami', 'Tampa', 'Jacksonville', 'B', 'easy', 'history', 2025, 1),
('Which city is home to the Steelers?', 'Cleveland', 'Pittsburgh', 'Cincinnati', 'Philadelphia', 'B', 'easy', 'history', 2025, 1),
('Which team drafted Tom Brady?', 'San Francisco 49ers', 'New York Jets', 'New England Patriots', 'Indianapolis Colts', 'C', 'easy', 'history', 2025, 1),
('Which team won Super Bowl XX?', 'Chicago Bears', 'San Francisco 49ers', 'Washington', 'New York Giants', 'A', 'easy', 'history', 2025, 1),
('What color penalty flag do NFL officials throw for most penalties?', 'Blue', 'Yellow', 'Red', 'Orange', 'B', 'easy', 'history/rules', 2025, 1),
('How many points is a field goal worth?', '2', '3', '4', '6', 'B', 'easy', 'history/rules', 2025, 1),

('How many passing yards did Matthew Stafford finish with as the 2025 regular-season passing leader?', '4,394', '4,552', '4,564', '4,707', 'D', 'hard', 'stat leader', 2025, 1),
('Who finished second in 2025 regular-season passing yards?', 'Dak Prescott', 'Drake Maye', 'Jared Goff', 'Patrick Mahomes', 'C', 'hard', 'stat leader', 2025, 1),
('How many rushing yards did James Cook finish with as the 2025 regular-season rushing leader?', '1,478', '1,585', '1,595', '1,621', 'D', 'hard', 'stat leader', 2025, 1),
('Who finished second in 2025 regular-season rushing yards?', 'Derrick Henry', 'Jonathan Taylor', 'Bijan Robinson', 'De''Von Achane', 'A', 'hard', 'stat leader', 2025, 1),
('How many receiving yards did Jaxon Smith-Njigba finish with as the 2025 regular-season receiving leader?', '1,637', '1,715', '1,793', '1,856', 'C', 'hard', 'stat leader', 2025, 1),
('Who led the NFL in receptions during the 2025 regular season?', 'Puka Nacua', 'Trey McBride', 'Ja''Marr Chase', 'Jaxon Smith-Njigba', 'A', 'hard', 'stat leader', 2025, 1),
('Which Browns defensive end won the Deacon Jones Sack Leader Award for the 2025 season?', 'Za''Darius Smith', 'Myles Garrett', 'Alex Wright', 'Ogbo Okoronkwo', 'B', 'hard', 'award winner', 2025, 1),
('Which head coach won AP Coach of the Year for the 2025 season?', 'Mike Macdonald', 'Dan Campbell', 'Mike Vrabel', 'Sean McVay', 'C', 'hard', 'award winner', 2025, 1),
('Which player won AP Comeback Player of the Year for the 2025 season?', 'Joe Burrow', 'Christian McCaffrey', 'Aaron Rodgers', 'Cooper Kupp', 'B', 'hard', 'award winner', 2025, 1),
('Which player won the Walter Payton NFL Man of the Year award for the 2025 season?', 'Bobby Wagner', 'Patrick Mahomes', 'Cameron Heyward', 'Dak Prescott', 'A', 'hard', 'award winner', 2025, 1),
('Which player won the Art Rooney Sportsmanship Award for the 2025 season?', 'Budda Baker', 'Justin Jefferson', 'George Kittle', 'Jalen Hurts', 'A', 'hard', 'award winner', 2025, 1),
('Which offensive lineman won Protector of the Year for the 2025 season?', 'Penei Sewell', 'Trent Williams', 'Joe Thuney', 'Lane Johnson', 'C', 'hard', 'award winner', 2025, 1),
('Which team did Jaxon Smith-Njigba play for in the fixed 2025 snapshot?', 'Seattle Seahawks', 'Los Angeles Rams', 'Cincinnati Bengals', 'Detroit Lions', 'A', 'hard', 'player-to-team', 2025, 1),
('Which team did Tetairoa McMillan play for when he won AP Offensive Rookie of the Year?', 'Carolina Panthers', 'Arizona Cardinals', 'Tennessee Titans', 'New England Patriots', 'A', 'hard', 'player-to-team', 2025, 1),
('Which team did Carson Schwesinger play for when he won AP Defensive Rookie of the Year?', 'Cleveland Browns', 'Chicago Bears', 'Jacksonville Jaguars', 'New York Jets', 'A', 'hard', 'player-to-team', 2025, 1),
('Which player was part of the Pro Football Hall of Fame Class of 2026 announced during the 2025 season honors?', 'Drew Brees', 'Eli Manning', 'Adrian Peterson', 'Rob Gronkowski', 'A', 'hard', 'history', 2025, 1),
('Which team completed the NFL''s only perfect season including a Super Bowl win?', '1985 Chicago Bears', '1972 Miami Dolphins', '2007 New England Patriots', '1999 St. Louis Rams', 'B', 'hard', 'history', 2025, 1),
('Which NFL team lost four straight Super Bowls in the early 1990s?', 'Minnesota Vikings', 'Denver Broncos', 'Buffalo Bills', 'Atlanta Falcons', 'C', 'hard', 'history', 2025, 1),
('Who is the NFL''s all-time rushing yards leader?', 'Walter Payton', 'Barry Sanders', 'Emmitt Smith', 'Adrian Peterson', 'C', 'hard', 'history', 2025, 1),
('Which franchise has the most total NFL championships when counting pre-Super Bowl titles?', 'Green Bay Packers', 'Pittsburgh Steelers', 'New England Patriots', 'Dallas Cowboys', 'A', 'hard', 'ring/count', 2025, 1),
('Who is the NFL''s all-time leader in career passing yards?', 'Drew Brees', 'Tom Brady', 'Peyton Manning', 'Brett Favre', 'B', 'hard', 'history', 2025, 1),
('Who holds the NFL record for most career touchdown passes?', 'Peyton Manning', 'Aaron Rodgers', 'Tom Brady', 'Drew Brees', 'C', 'hard', 'history', 2025, 1),
('Who holds the NFL single-season record for touchdown passes?', 'Tom Brady', 'Peyton Manning', 'Patrick Mahomes', 'Dan Marino', 'B', 'hard', 'history', 2025, 1),
('Who holds the NFL single-season record for receiving yards?', 'Jerry Rice', 'Calvin Johnson', 'Cooper Kupp', 'Justin Jefferson', 'B', 'hard', 'history', 2025, 1),
('Who holds the NFL single-season record for rushing yards?', 'Eric Dickerson', 'Adrian Peterson', 'O.J. Simpson', 'Barry Sanders', 'A', 'hard', 'history', 2025, 1),
('Which head coach has the most Super Bowl wins?', 'Bill Walsh', 'Chuck Noll', 'Bill Belichick', 'Andy Reid', 'C', 'hard', 'ring/count', 2025, 1),
('How many Super Bowl MVP awards did Tom Brady win?', '3', '4', '5', '6', 'C', 'hard', 'ring/count', 2025, 1),
('Which team has appeared in the most Super Bowls?', 'Pittsburgh Steelers', 'Dallas Cowboys', 'New England Patriots', 'San Francisco 49ers', 'C', 'hard', 'ring/count', 2025, 1),
('Which player famously returned the opening kickoff of Super Bowl XLI for a touchdown?', 'Devin Hester', 'Deion Sanders', 'Tyreek Hill', 'Cordarrelle Patterson', 'A', 'hard', 'history', 2025, 1),
('Which franchise was originally known as the Houston Oilers?', 'Houston Texans', 'Tennessee Titans', 'Indianapolis Colts', 'Jacksonville Jaguars', 'B', 'hard', 'history', 2025, 1),
('In what year did the AFL-NFL merger fully take effect?', '1966', '1968', '1970', '1972', 'C', 'hard', 'history', 2025, 1),
('Who is the NFL''s all-time sacks leader?', 'Reggie White', 'Bruce Smith', 'Kevin Greene', 'T.J. Watt', 'B', 'hard', 'history', 2025, 1),
('Which player is the NFL''s all-time leader in receptions?', 'Larry Fitzgerald', 'Tony Gonzalez', 'Jerry Rice', 'Travis Kelce', 'C', 'hard', 'history', 2025, 1),
('Which quarterback started and won two Super Bowls for the New York Giants against the Patriots?', 'Phil Simms', 'Eli Manning', 'Kurt Warner', 'Jeff Hostetler', 'B', 'hard', 'history', 2025, 1),
('Which player won the 1982 NFL MVP award as a kicker?', 'Morten Andersen', 'Gary Anderson', 'Mark Moseley', 'Jan Stenerud', 'C', 'hard', 'history', 2025, 1),
('Which team did Peyton Manning win his second Super Bowl with?', 'Indianapolis Colts', 'Denver Broncos', 'Tennessee Titans', 'New Orleans Saints', 'B', 'hard', 'history', 2025, 1),
('Which team selected Aaron Rodgers in the first round of the 2005 NFL Draft?', 'San Francisco 49ers', 'Green Bay Packers', 'New York Jets', 'Denver Broncos', 'B', 'hard', 'history', 2025, 1),
('Which wild-card team won Super Bowl LV?', 'Kansas City Chiefs', 'Tampa Bay Buccaneers', 'Los Angeles Rams', 'Buffalo Bills', 'B', 'hard', 'history', 2025, 1),
('Which player has the most career interceptions in NFL history?', 'Paul Krause', 'Rod Woodson', 'Ed Reed', 'Night Train Lane', 'A', 'hard', 'history', 2025, 1),
('Who was the first overall pick in the 1998 NFL Draft?', 'Ryan Leaf', 'Peyton Manning', 'Charles Woodson', 'Randy Moss', 'B', 'hard', 'history', 2025, 1);
